### ISSUE TITLE
exception in get_all_data prevents function from working

### ISSUE THREAD

**Issue by dr-waterstorm** [Vip0r/vartastorage#1]
I just tried your package. It works perfectly well for individual values, however get_all_data() fails on getting the "total production power". The raised error prevents me from using the function at all.
```
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vartastorage.vartastorage import VartaStorage
>>> varta = VartaStorage('192.168.178.185',502)
>>> varta.get_all_data()
Traceback (most recent call last):
  File "/home/jens/.local/lib/python3.10/site-packages/vartastorage/client.py", line 161, in get_total_production_power
    ).decode_16bit_float()
AttributeError: 'BinaryPayloadDecoder' object has no attribute 'decode_16bit_float'. Did you mean: 'decode_32bit_float'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jens/.local/lib/python3.10/site-packages/vartastorage/client.py", line 48, in get_all_data
    out["total_production_power"] = self.get_total_production_power()
  File "/home/jens/.local/lib/python3.10/site-packages/vartastorage/client.py", line 167, in get_total_production_power
    raise ValueError("An error occured while polling total production power. Please check your connection")
ValueError: An error occured while polling total production power. Please check your connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jens/.local/lib/python3.10/site-packages/vartastorage/vartastorage.py", line 15, in get_all_data
    data = self.client.get_all_data()
  File "/home/jens/.local/lib/python3.10/site-packages/vartastorage/client.py", line 55, in get_all_data
    raise ValueError("An error occured while trying to poll all data fields. Please check your connection")
ValueError: An error occured while trying to poll all data fields. Please check your connection
```

It would be nice if this would be handled more gracefully. If getting one value fails, it would be nice to still get and show all other values.

**Comment by Vip0r** [comment]
Hey!

as also pointed out in my current PR to HA Core i now integrated the CGI endpoints you made me aware of. As this will also provide the same data i removed this part from the modbus client of the code and you should not get this errors any longer.

Really appreciate your feedback. Please let me know if you have any other issues.

**Comment by skar84** [comment]
Hi Vip0r,

Firstly, I'd like to thank you for this nice module.
It used to work pretty well - according to your statement, it still should and I definitely can easily access the total production data, however I have not found any option (neither in raw cgi data nor in your module) for the current production power.
Could you please provide some additional info, since this used to be the only way calculating the current in-house-consumption prior to V0.2.3.

Thank you very much in advance.
