### ISSUE TITLE
Not working with Pulse Neo

### ISSUE THREAD

**Issue by Kallenberger** [Vip0r/vartastorage#2]
Hi,

I'm getting an Error whlie trying to "get_all_data()" with the varta Pulse Neo:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/anaconda3/envs/hass_test/lib/python3.10/site-packages/vartastorage/client.py:55, in Client.get_all_data(self)
     54 energytotals = self.get_energy_cgi()
---> 55 out["EGrid_AC_DC"] = energytotals["EGrid_AC_DC"]
     56 out["EGrid_DC_AC"] = energytotals["EGrid_DC_AC"]

TypeError: 'NoneType' object is not subscriptable
```

Probably because the Pulse Neo doesn't have an XML-API (https://www.varta-ag.com/fileadmin/varta_storage/downloads/products/energy/varta-pulse/Datasheet_VARTA_pulse_en_17.pdf)
![grafik](https://user-images.githubusercontent.com/8975318/192370944-6b20395e-08a5-4dad-8c05-9630cf0e6ea2.png)

The Pulse Neo seems to respond with 404 on the requested paths:
![grafik](https://user-images.githubusercontent.com/8975318/192372824-355bd5b3-6e99-4b02-9203-ae2b1d5f7cd8.png)

All the Modbus-Values seem to load just fine
![grafik](https://user-images.githubusercontent.com/8975318/192371785-d50ef783-e2b8-41c0-9f0b-3559264ea917.png)

Would it be possible to set 0 (or some sort of default) Values instead of Null?

Thanks and let me know if you need any further information!

**Comment by Vip0r** [comment]
Hey Kallenberger,
i adjusted this section in the code. In the case that the cgi endpoint is not available the functions now should return 0 for all values. Could you give it a try? 

Let me know if you still have issues
