### ISSUE TITLE
requests not installed and some other minor comments

### ISSUE THREAD

**Issue by Santobert** [Vip0r/vartastorage#4]
Hi. Thank you very much for your great work! I've tested your package and it seems to work fine. Nevertheless, I have some minor comments/questions:

- you're using the requests package without listing it as dependency. In a fresh environment the package will fail since `requests` is not installed
- the `cgi` methods won't convert text to int. Therefore, `EGrid_AC_DC` and so on are stored as text, which could lead to issues later on. Right now, this seems to be no problem.
- Personally, I would try to catch specific exceptions instead of an broad `Exception` (e.g. [here](https://github.com/Vip0r/vartastorage/blob/main/src/vartastorage/client.py#L192)). Especially for the use in HomeAssistant it could be helpful to know whether the connection is broken or the returned data has an unexpected format. Also, it is usually better to fail gently (e.g. by checking the status_code) than using `try...except`, since collecting a stack trace is expensive.

If you disagree with some or all of the points, feel free to close or delete this issue :)
If you want me to create a PR, please say so. I can't promise anything, but I will try to find some time.

**Comment by Vip0r** [comment]
hey @Santobert : 

Thank you very much for your feedback. I agree to all your points. if you find some spare time, i would appreciate any support. Feel free to create a PR

**Comment by Vip0r** [comment]
i have fixed the issues regarding the missing requirement and i also converted the cgi data to integers.

There is now a new release 0.2.7. This release also now allow us to seperate between cgi and modbus calls.

Before i further work on the HA(CS) integration it would be great if you can take a look. Any PRs to improve the code are welcome
